public static class Names 
{
    public static readonly string[] names = new string[]
    {
        "Sir Hugo the Hairy Headed Hooligan",
        "Lady Lola the Loony",
        "Lord Lionel the Long Legged Loon",
        "Lady Leona the Laughing Lunatic",
        "Sir Sammy the Sappy",
        "Lady Sally the Silly",
        "Lord Billy the Bumbling Buffoon",
        "Lady Beverly the Bouncing Bimbo",
        "Sir Eddie the Eccentric",
        "Lady Ellie the Energetic",
        "Lord Rudy the Rambunctious Rascal",
        "Lady Rachel the Radiant Rascal",
        "Sir Leo the Loony",
        "Lady Linda the Lively",
        "Lord Larry the Lopsided",
        "Lady Lucy the Loony",
        "Sir Phil the Phunny",
        "Lady Pam the Peculiar",
        "Lord Morty the Mirthful Moron",
        "Lady Molly the Mischievous",
        "Sir Timmy the Taunting Twit",
        "Lady Toni the Tickling Twit",
        "Lord Jimmy the Jolly Joker",
        "Lady Joan the Joyful Jester",
        "Sir Harry the Hilarious",
        "Lady Hedda the Hilarious",
        "Lord Barry the Bouncing Blunder",
        "Lady Bonnie the Bouncing Blonde",
        "Sir Chris the Chuckling Clown",
        "Lady Cathy the Chuckling Clown",
        "Sir Walter the Witty Wacko",
        "Lady Wendy the Wacky Witch",
        "Lord Rupert the Rambunctious Rascal",
        "Lady Rosalind the Radiant Rascal",
        "Sir Colin the Clownish",
        "Lady Caroline the Chuckling Cutie",
        "Lord Elliot the Eccentric Elf",
        "Lady Eleanor the Entertaining Elf",
        "Sir Hector the Hilarious Harlequin",
        "Lady Henrietta the Hysterical Harlequin",
        "Lord Lionel the Laughing Loon",
        "Lady Louisa the Loony Lady",
        "Sir Nathan the Naughty Noble",
        "Lady Nina the Naughty Noble",
        "Lord Oliver the Outlandish",
        "Lady Olivia the Outlandish",
        "Sir Percival the Playful Puck",
        "Lady Penelope the Playful Puck",
        "Lord Quentin the Quirky Quail",
        "Lady Queenie the Quirky Quail",
        "Sir Roland the Rambunctious Rascal",
        "Lady Regina the Radiant Rascal",
        "Lord Sterling the Silly Squire",
        "Lady Sophie the Silly Squire",
        "Sir Theodore the Taunting Twit",
        "Lady Theodora the Taunting Twit",
        "Lord Jimmy the Jolly Joker",
        "Lady Joan the Joyful Jester",
        "Sir Harry the Hilarious",
        "Lady Hedda the Hilarious",
        "Lord Barry the Bouncing Blunder",
        "Lady Bonnie the Bouncing Blonde",
        "Sir Chris the Chuckling Clown",
        "Lady Cathy the Chuckling Clown",
        "Sir Fred the Flaky Fool",
        "Lady Fran the Frolicking Fool",
        "Lord Jeff the Jesting Jester",
        "Lady Julie the Joyful Jester",
        "Sir Mick the Merry Monarch",
        "Lady Mandy the Mischievous Maid",
        "Lord Nick the Naughty Numbskull",
        "Lady Nancy the Nonsensical Nudge",
        "Sir Rob the Rambunctious Rascal",
        "Lady Rachel the Radiant Rascal",
        "Lord Tom the Taunting Twit",
        "Lady Tina the Ticking Twit",
        "Sir Vic the Vexing Vandal",
        "Lady Val the Vivacious Vixen",
        "Lord Wes the Whimsical Wacko",
        "Lady Wendy the Whimsical Wacko",
        "Sir Yank the Yapping Yokel",
        "Lady Yolanda the Yipping Yokel",
        "Lord Zack the Zany Zebra",
        "Lady Zoe the Zesty Zebra",
        "Sir Alan the Amusing Ape",
        "Lady Abby the Amusing Ape",
        "Lord Bob the Bouncing Baboon",
        "Lady Beth the Bouncing Baboon",
        "Sir Chad the Chuckling Chimpanzee",
        "Lady Cindy the Chuckling Chimpanzee",
        "Lord Dave the Daring Dork",
        "Lady Debbie the Daring Dork",
        "Sir Evan the Eccentric Elephant",
        "Lady Eve the Eccentric Elephant"
    };
}
