/// <summary>
/// This script is a static wrapper for all possible names for adventurers.
/// </summary>
public static class Names 
{
    public static readonly string[] names = new string[]
    {
        "Hugo the Hairy Hooligan",
        "Lady Lola the Loony",
        "Lionel the Long Legged Loon",
        "Leona the Laughing Lunatic",
        "Sir Sammy the Sappy",
        "Lady Sally the Silly",
        "Billy the Bumbling Buffoon",
        "Beverly the Bouncing Bimbo",
        "Sir Eddie the Eccentric",
        "Lady Ellie the Energetic",
        "Rudy the Rambunctious Rascal",
        "Rachel the Radiant Rascal",
        "Sir Leo the Loony",
        "Lady Linda the Lively",
        "Lord Larry the Lopsided",
        "Lady Lucy the Loony",
        "Sir Phil the Phunny",
        "Lady Pam the Peculiar",
        "Morty the Mirthful Moron",
        "Molly the Mischievous",
        "Timmy the Taunting Twit",
        "Toni the Tickle",
        "Jimmy the Jolly Joker",
        "Joan the Joyful Jester",
        "Sir Harry the Hilarious",
        "Lady Hedda the Hilarious",
        "Barry the Bouncing Blunder",
        "Bonnie the Bouncing Blonde",
        "Chris the Chuckling Clown",
        "Cathy the Chuckling Clown",
        "Sir Walter the Witty Wacko",
        "Lady Wendy the Wacky Witch",
        "Rupert the Rascal",
        "Lady Rosalind Rascal",
        "Sir Colin the Clownish",
        "Caroline the Chuckling Cutie",
        "Elliot the Eccentric Elf",
        "Eleanor the Entertaining Elf",
        "Hector the Hilarious Harlequin",
        "Henrietta the Hysterical",
        "Lord Lionel the Laugh",
        "Lady Louisa the Loony",
        "Sir Nathan the Naughty",
        "Lady Nina the Naughty",
        "Oliver the Outlandish",
        "Olivia the Outlandish",
        "Percival the Puck",
        "Penelope the Playful",
        "Lord Quentin the Quail",
        "Queenie the Quirk",
        "Sterling the Silly Squire",
        "Sophie the Silly Squire",
        "Lord Jimmy the Jolly Joker",
        "Lady Joan the Joyful Jester",
        "Sir Harry the Hilarious",
        "Lady Hedda the Hilarious",
        "Lord Bouncing Blunder",
        "Lady Barry the Blonde",
        "Chris the Chuckling Clown",
        "Sir Fred the Flaky Fool",
        "Lady Fran the Frolicking Fool",
        "Lord Jeff the Jesting Jester",
        "Lady Julie the Joyful Jester",
        "Mick the Merry Monarch",
        "Mandy the Mischievous Maid",
        "Leo the Loony",
        "Linda the Lively",
        "Larry the Lopsided",
        "Lucy the Loony",
        "Phil the Phunny",
        "Pam the Peculiar",
        "Sir Vic the Vexing Vandal",
        "Lady Val the Vivacious Vixen",
        "Lord Wes the Whimsical Wacko",
        "Lady Wendy the Whimsical Wacko",
        "Sir Yank the Yapping Yokel",
        "Lady Yolanda the Yipping Yokel",
        "Lord Zack the Zany Zebra",
        "Lady Zoe the Zesty Zebra",
        "Sir Alan the Amusing Ape",
        "Lady Abby the Amusing Ape",
        "Bob the Bouncing Baboon",
        "Beth the Bouncing Baboon",
        "Chad the Chimpanzee",
        "Cindy the Chuckle",
        "Dave the Daring Dork",
        "Debbie the Dork",
        "Sir Evan the Eccentric",
        "Lady Eve the Eccentric"
    };
}
